### CONFIGURATION AND RUN SETUP FOR PYOCCULT ###
    
### SEARCH SETUP

ct, days, spn = "2026-10-01T00:00:00", 20, 3600

# if targets.py file was created it is automatically used, delete it to use a manaual list as the example below after ImportError:
try:
    from targets import targets, target_names   # try to used targets.py, auto generated by pyoccul_pick.py tool -- or manully if you wish, simply define targets = [ "218001", ...]
except ImportError:
    targets = ["218001", "305580", "111287", "115181", "229912", "111286", "54653", "70141", "4272"]  # uses this manual list if targets.py is not present
    target_names = {} # currently not required. A id: name dict
    
max_shadow_dist = 200  ## in km: travel distance from observer location

### CONFIG OBSERVER

LAT = 40.9541175
LON = -72.92614552
ELE = 69

MAG_MIN = 20
MIN_STAR_ALT = 10.0     # deg, use the same constants in both gates
MAX_SUN_ALT  = -6.0     # deg, try -12 for faint stars
ALT_MARGIN   = 3.0      # early gate is looser than the final one, so it never rejects a real event

### CONFIG OUTPUT

hits_output_cvs_file = 'hits_log.csv'

write_maps = True
map_dir = "maps"
default_sigma3_km = 10.0

cache_path = "/dev/shm"  ## good for Linux, but volatile after reboot

### Init, Cleanups, ToDO clean SHM cache?
earth_pck_max_age = 7 ## days for earth pck to expire/auto update
force_cleanup = False

