#!.venv/bin/python3
"""pyoccult_picks.py - saved pick results per site and window, so a search can reuse them instead of picking again.

pyoccult_pick.py saves every run for a named site as a pair in picks/ (config picks_dir):
    picks/<site>__<start>_<days>d.py     importable target list (targets, target_names, pick_meta)
    picks/<site>__<start>_<days>d.csv    all events of that pick (as pick_events.csv)
A new pick of the same site and window replaces the pair. pyoccult.py (targets_source = "auto") uses the newest saved
pick of its site whose window covers the search window; without one it falls back to targets.py / the config list.

    python pyoccult_picks.py list [site]       # saved picks
    python pyoccult_picks.py import            # save the current targets.py + pick_events.csv under their site/window

Standard library only.
"""
import argparse, os, re, runpy, shutil, sys
from datetime import date, timedelta

DIR = "picks"
HEADER = re.compile(r"^# events (\d{4}-\d\d-\d\d) \+ ([\d.]+) d, site ([^,]+),", re.M)


def _safe(site):
    return re.sub(r"[^\w.-]+", "_", str(site)).strip("_") or "site"


def paths(site, start, days, folder=DIR):
    """(targets .py, events .csv) of the saved pick for this site and window."""
    stem = os.path.join(folder, f"{_safe(site)}__{str(start)[:10]}_{float(days):g}d")
    return stem + ".py", stem + ".csv"


def _read(py):
    """dict(site, start, days, picked, targets, names, py, csv) of one saved pick, or None if unreadable."""
    try:
        mod = runpy.run_path(py)
    except Exception:
        return None
    meta = mod.get("pick_meta") or {}
    if not meta:                                          # targets.py style: window and site from the header line
        with open(py, encoding="utf-8") as f:
            head = f.read(4000)
        m, g = HEADER.search(head), re.search(r"^# generated by .* on (\d{4}-\d\d-\d\d \d\d:\d\d) UTC", head, re.M)
        if not m:
            return None
        meta = dict(start=m[1], days=float(m[2]), site=m[3].strip(), picked=g[1].replace(" ", "T") if g else "")
    return dict(site=str(meta["site"]), start=str(meta["start"])[:10], days=float(meta["days"]),
                picked=meta.get("picked") or "", lat=meta.get("lat"), lon=meta.get("lon"), targets=[str(t) for t in mod.get("targets", [])],
                names=mod.get("target_names", {}), py=py, csv=os.path.splitext(py)[0] + ".csv")


def list_for(site=None, folder=DIR):
    """Saved picks (of one site, or all), newest window first."""
    if not os.path.isdir(folder):
        return []
    out = []
    for f in sorted(os.listdir(folder)):
        if f.endswith(".py") and "__" in f and (site is None or f.startswith(_safe(site) + "__")):
            p = _read(os.path.join(folder, f))
            if p and (site is None or p["site"] == str(site)):
                out.append(p)
    return sorted(out, key=lambda p: (p["start"], p["picked"]), reverse=True)


def end_of(p):
    return (date.fromisoformat(p["start"]) + timedelta(days=p["days"])).isoformat()


def moved(p, lat, lon, tol_deg=0.01):
    """True if the pick was made for another position of the site (by more than ~1 km)."""
    return (None not in (lat, lon, p.get("lat"), p.get("lon"))
            and max(abs(p["lat"] - lat), abs((p["lon"] - lon + 180) % 360 - 180)) > tol_deg)


def best_for(site, start, days, folder=DIR, lat=None, lon=None):
    """The saved pick of this site whose window covers start .. start+days (newest pick first), or None. With lat/lon,
    picks made before the site was moved are skipped."""
    s0 = str(start)[:10]
    s1 = (date.fromisoformat(s0) + timedelta(days=float(days))).isoformat()
    cover = [p for p in list_for(site, folder) if p["start"] <= s0 and end_of(p) >= s1 and not moved(p, lat, lon)]
    return max(cover, key=lambda p: (p["picked"], p["start"])) if cover else None


def describe(p):
    return (f"saved pick {p['site']} {p['start']} + {p['days']:g} d"
            + (f" (picked {p['picked'][:16].replace('T', ' ')} UTC)" if p["picked"] else "") + f", {len(p['targets'])} targets")


def import_current(targets_py="targets.py", events_csv="pick_events.csv", folder=DIR):
    """Save an existing targets.py (+ pick_events.csv) under the site and window named in its header."""
    p = _read(targets_py)
    if p is None:
        sys.exit(f"{targets_py}: no readable header line '# events <start> + <days> d, site <name>, ...'")
    os.makedirs(folder, exist_ok=True)
    py, csv = paths(p["site"], p["start"], p["days"], folder)
    shutil.copyfile(targets_py, py)
    if os.path.isfile(events_csv):
        shutil.copyfile(events_csv, csv)
    print(f"saved {py}" + (f" and {csv}" if os.path.isfile(events_csv) else ""))


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=["list", "import"])
    ap.add_argument("site", nargs="?")
    a = ap.parse_args()
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    if a.cmd == "import":
        import_current()
    else:
        for p in list_for(a.site):
            print(f"{p['site']:20s} {p['start']} + {p['days']:g} d  picked {p['picked'][:16] or '?':16s}  "
                  f"{len(p['targets']):3d} targets  {p['py']}")
