### CONFIGURATION AND RUN SETUP FOR PYOCCULT ###
# Your copy lives in the data folder next to sites.py (created from src/pyoccult/templates/pyoccult_config.py, not in
# git). Settings missing here keep the template's default.
import os as _os, tempfile as _tempfile
    
### SEARCH SETUP

ct, days, spn = "2026-10-01T00:00:00", 20, 3600   # start (UTC), days to search, window length in s ("windows" mode only)

# if targets.py file was created it is automatically used, delete it to use a manaual list as the example below after ImportError:
try:
    from targets import targets, target_names   # try to used targets.py, auto generated by pyoccult pick -- or manully if you wish, simply define targets = [ "218001", ...]
    #targets.append(["218001", "305580", "111287", "115181", "229912", "111286", "54653", "70141", "4272"])
except ImportError:
    targets = ["218001", "305580", "111287", "115181", "229912", "111286", "54653", "70141", "4272"]  # uses this manual list if targets.py is not present
    target_names = {} # currently not required. A id: name dict
# "auto": a search uses the saved pick (picks_dir, written by pyoccult pick) of its site whose window covers the
# search window, else the list above; "list": always the list above
targets_source = "auto"
picks_dir = "picks"
    
max_shadow_dist = 20  ## in km: travel distance from observer location

search_mode = "corridor"   # "corridor": stars along each path from the local Gaia copy (fast); "windows": old per-window archive cones
star_parallax = True       # astrometric corrections of the star direction (ABOUT.md Part 6): the star seen from the
light_deflection = True    # Earth (Gaia parallax), and the light bending by Sun, Jupiter, Saturn (star minus asteroid)
min_mag_drop = 0.1         # mag; events with a smaller drop are not logged (also sets the Gaia magnitude cap per asteroid)
corridor_step_s = 600      # s, coarse path step for the corridor candidate scan
gaia_local_dir = "gaia_dr3_g18"  # folder of the local Gaia copy, required by corridor mode (pyoccult setup, or pyoccult gaia build)
gaia_local_gmax = 13.0     # faintest G kept when building the local copy (~11 GB for 18; a new value needs a new folder)
gaia_local_dir = _os.environ.get("PYOCCULT_CATALOG", gaia_local_dir)   # choose another catalog folder for one run

### CONFIG OBSERVER: sites, their view and equipment

# The site comes from sites.py (your sites, not in git), else from sites_example.py (in pyoccult/templates). Choose one by name with the
# environment variable PYOCCULT_SITE (default: default_site in that file). A site has lat, lon, ele and may set any of
# the keys below; the values here are the defaults for keys a site leaves out.
try:
    from sites import sites, default_site
except ImportError:
    from pyoccult.templates.sites_example import sites, default_site
site_name = _os.environ.get("PYOCCULT_SITE", default_site)
if site_name not in sites:
    raise SystemExit(f"site {site_name!r} not in sites.py (known: {', '.join(sites)})")
site = sites[site_name]

LAT = site["lat"]                                  # latitude, deg
LON = site["lon"]                                  # longitude, deg, negative is west
ELE = site["ele"]                                  # elevation, m

# view
MIN_STAR_ALT = site.get("min_alt", 10.0)           # deg, lowest usable star altitude (trees, houses, haze)
MAX_SUN_ALT = site.get("max_sun_alt", -6.0)        # deg, the Sun must be below this (try -12 for faint stars)
max_shadow_dist = site.get("reach_km", max_shadow_dist)   # km, travel distance from the site (default: search setup)
ALT_MARGIN = 3.0                                   # early gate is looser than the final one, never rejects a real event

# atmospheric extinction for lower altitudes, mag per airmass: a star at altitude h counts as fainter by
# atm_extinction * (airmass(h) - 1) in the observability test (0 = off; ~0.2 typical, ~0.3 hazy or light-polluted).
# A site's `extinction` key overrides it.
atm_extinction = 0.0

# equipment: OWC's General Observability Criterion. An event is observable if
#   StarMag < 5 log10(aperture_cm) + 2.5 log10(MaxDuration / frames) + 8.5 + mag_adjust
# (mag_adjust > 0 for better conditions: dark sky, sensitive camera; < 0 for worse), optionally with atmospheric
# extinction at the star's altitude. The faintest star searched (MAG_MIN) is the one that is observable at the
# longest usable exposure max_exp_s (= MaxDuration / frames), unless the site gives mag_limit.
pick_aperture_cm = site.get("aperture_cm", 25.0)   # telescope aperture, cm
pick_frames = site.get("frames", 4)                # detection frames
pick_mag_adjust = site.get("mag_adjust", 0.0)      # OWC MagAdjust, mag
pick_extinction = site.get("extinction", atm_extinction)   # mag per airmass (see atm_extinction above)
pick_min_dur_s = site.get("min_dur_s", 0.4)        # hard limit: shortest event, s
pick_max_exp_s = site.get("max_exp_s", 0.64)       # longest usable exposure, s (25 cm: G 15.0, as OWC)
_lim = (5 * __import__("math").log10(pick_aperture_cm) + 2.5 * __import__("math").log10(pick_max_exp_s)
        + 8.5 + pick_mag_adjust)
MAG_MIN = min(site.get("mag_limit", round(_lim, 1)), gaia_local_gmax)   # faintest star searched
pick_cam_limit = MAG_MIN                           # same limit for the pick tool

# camera, for the event preview: field of view from the focal length and the sensor size
camera_focal_mm = site.get("focal_mm", 100.0 * pick_aperture_cm)   # focal length, mm (default f/10)
camera_sensor_mm = tuple(site.get("sensor_mm", (5.6, 3.2)))        # sensor width, height, mm (5.6 x 3.2: e.g. IMX290)

### CONFIG PICK TOOL (pyoccult pick: event finder over all asteroids; equipment comes from the site above)

pick_hmax = 17.0         # asteroids with H below this (pyoccult pick --all: every numbered asteroid)

### CONFIG OUTPUT

hits_output_cvs_file = 'hits_log.csv'

write_maps = True
map_dir = "maps"
write_globes = True         # Occult-style whole-Earth plot per event (<stem>_globe.svg in map_dir; needs write_maps)
globe_style = "color"       # "color" (sea, land, night side, like OWC) or "lines" (black on white, like Occult)
write_previews = True       # event preview image (star field, camera frame, asteroid track) per hit, as SVG in map_dir
preview_mag_limit = 16.0    # faintest star drawn (Gaia G)
preview_field_factor = 3.0  # preview field = this x the camera field (at least 10 arcmin)
default_sigma3_km = 10.0

## cache folder for all tools (asteroid SPKs, SBDB downloads). /dev/shm is RAM on Linux (fast, emptied on reboot);
## elsewhere the system temp folder is used. Set any folder here, e.g. cache_path = "C:/pyoccult_cache"
cache_path = "/dev/shm" if _os.path.isdir("/dev/shm") else _tempfile.gettempdir()

sbdb_max_age_days = 30  ## asteroid size data (SBDB) is cached in cache_path and refetched after this many days

### Init, Cleanups, ToDO clean SHM cache?
earth_pck_max_age = 7 ## days for earth pck to expire/auto update
force_cleanup = False
